### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by dnet** [DaveRandom/cloud-to-butt-mozilla#9]
I'd like to use your code, so if you'd allow this, please add a FLOSS license like MIT, BSD or GPL.

**Comment by DaveRandom** [comment]
Apologies for not responding to this sooner, I've been away from FOSS for a while due to other commitments.

I'll try to get a license file added this week, it will be MIT, please feel free to do whatever you want with this code. If you make your millions from it, please send me some milk as I have run out and cannot be bothered walking to the shop even though I really want a cup of tea.

**Comment by dnet** [comment]
Sure, thanks!
